name: mRemoteNG
description: The next generation of mRemote, open source, tabbed, multi-protocol, remote connections manager.
url: https://newsite.mremoteng.org
baseurl: 
repository: mRemoteNG/mRemoteNG
exclude: [README.md, Gemfile, Gemfile.lock]
permalink: pretty
paginate: 5
paginate_path: /posts/:num/

defaults:
  -
    scope:
      path: ''
      type: pages
    values:
      layout: default
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

gems:
  - jekyll-feed
  - jekyll-metions
  - jekyll-sitemap
  - jemoji
