name: mRemoteNG
description: The next generation of mRemote, open source, tabbed, multi-protocol, remote connections manager.
url: https://mRemoteNG.github.io
baseurl: /mRemoteNG
repository: mRemoteNG/mRemoteNG
exclude: [README.md, Gemfile, Gemfile.lock]
permalink: pretty

defaults:
  -
    scope:
      path: ''
      type: pages
    values:
      layout: default
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

gems:
  - jekyll-feed
  - jekyll-metions
  - jekyll-sitemap
  - jemoji
