version: 1.76.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration:
- Release
- Release Portable
platform: x86
clone_depth: 1
install:
- ps: C:\projects\mremoteng\mRemoteV1\Resources\CitrixReceiver.exe DONOTSTARTCC=1 ENABLE_SSON="No" /silent | out-null
before_build:
- cmd: nuget restore
build:
  project: mRemoteV1.sln
  verbosity: normal
test:
  assemblies:
    only:
    - mRemoteNGTests\bin\$(configuration)\mRemoteNGTests.dll
artifacts:
	- path: 'C:\projects\mremoteng\mRemoteV1\Release\*.msi'
	  name: mRemoteNG-installer.msi
		  
	- path: 'C:\projects\mremoteng\mRemoteV1\Release\*.zip'
	  name: mRemoteNG-portable.zip
